# Note  : *** the batch_size should be equal to the gpus number at the test phase!!! ***
data_cfg:
  dataset_name: Gai3D
  dataset_root: your path
  dataset_partition: ./misc/partitions/Gait3D.json
  num_workers: 1
  remove_no_gallery: false
  test_dataset_name: Gait3D

evaluator_cfg:
  enable_distributed: true
  enable_float16: false 
  restore_ckpt_strict: true
  restore_hint: 210000
  save_name: HSTL_Gait3D
  eval_func: evaluation_Gait3D # identification_real_scene # identification_GREW_submission
  sampler:
    batch_size: 8
    sample_type: all_ordered
    type: InferenceSampler

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 16
    type: CrossEntropyLoss
    log_accuracy: true
    label_smooth: true
    log_prefix: softmax

model_cfg:
  model: HSTL_Gait3D
  channels: [32, 64, 128, 256]
  class_num: 3000

optimizer_cfg:
  lr: 0.1
  momentum: 0.9
  solver: SGD
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 80000
    - 150000
    - 200000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true
  with_test: false
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 10000
  save_name: HSTL_Gait3D
  sync_BN: true
  total_iter: 210000
  sampler:
    batch_shuffle: true
    batch_size:
      - 32
      - 8
    frames_num_fixed: 30
    frames_skip_num: 4
    sample_type: fixed_ordered
    type: TripletSampler
